server:
  port: 8080

quarkus:
  application:
    name: usermanagement
  banner:
    path: banner.txt
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
#      url: jdbc:postgresql://postgres:5432/usermanagement
      url: jdbc:postgresql://host.docker.internal:5432/usermanagement
  hibernate-orm:
    database:
      generation: drop-and-create
