quarkus:
  http:
    port: 8080
  application:
    name: customer

  datasource:
    jdbc:
      url: jdbc:postgresql://db:5432/your_database
    username: your_username
    password: your_password

  hibernate-orm:
    database:
      generation: drop-and-create
    dialect: org.hibernate.dialect.PostgreSQLDialect
    log:
      sql: true
      format-sql: true

  services:
    postgres:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - postgres
      restart: unless-stopped
    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
      networks:
        - postgres
      restart: unless-stopped
