services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usermanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.jvm
#    container_name: usermanagement
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@postgres:5432/usermanagement
#    ports:
#      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
